name: Test Dev Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/default/**"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "src/default/**"
      - ".github/workflows/test.yaml"

jobs:
  build-and-run:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Build and run Dev Container
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/default
          push: never
          runCmd: |
            docker info
            docker run --rm hello-world
